name: sikp_mobile
description: "Sistem Informasi Kerja Praktek Teknik Informatika Unkhair"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.1.0
  firebase_core: ^2.27.0
  firebase_auth: 4.16.0
  cloud_firestore: ^4.15.0
  pdf: ^3.11.0
  printing: 5.13.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_apk.png"

  adaptive_icon_foreground: "assets/images/logo_apk.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_unkhair.png
    - assets/images/logo_apk.png 